<?php

/*
 * Copyright (c) 2014 The "Show PGP/MIME plugin for Roundcube" Authors
 *
 * Licensed under GNU Affero General Public License v3
 * <https://gnu.org/licenses/agpl>.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

$labels = array();
$labels['show_pgp_mime_body_prefix'] = 'Dies ist eine mit PGP/MIME verschlüsselte Nachricht. Sie können Sie mit Addons wie Mailvelope entschlüsseln, um sie im Webmailer zu lesen.';
$labels['show_pgp_mime_prefs_label'] = 'PGP/MIME Nachrichten anzeigen (verschlüsselt)';

