<?php

/*
 * Localization file of the PGP/MIME plugin for Roundcube
 * Copyright (c) 2015 Dinahosting SL, Dinahosting translation team 
 *
 * Licensed under GNU Affero General Public License v3
 * <https://gnu.org/licenses/agpl>.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$labels = array();
$labels['show_pgp_mime_body_prefix'] = 'Mezu hau PGP/MIME zifratua da. Posta bezero honetan mezua irakurtzeko Mailvelope osagarriarekin egin dezakezu. .';
$labels['show_pgp_mime_prefs_label'] = 'PGP/MIME (enkriptatuak) mezuak adierazi';

